name: 'Publish Conda'
description: 'Build conda pkg and Publish (forked from Fatih C Akyon)'
author: 'Carlos Pascual'
branding:
  icon: 'package'
  color: 'green'
inputs:
  subdir:
    description: 'Sub-directory with conda recipe'
    default: '.'
  anacondatoken:
    description: 'Anaconda access token'
  platforms:
    description: 'Platforms to publish [osx/linux/win]'
    default: 'win osx linux'
runs:
  using: 'docker'
  image: 'Dockerfile'
